extends SceneTree
## Ballistic calibration tool (headless). Entry point: tools/ballistics/calibrate.sh
##
## User arguments (after "--"):
##   --report=<absolute path>   write the Markdown report there (always printed to stdout)
##   --write-metrics            save the calibrated values into GameMetrics.DEFAULT_PATH

func _initialize() -> void:
	var args: PackedStringArray = OS.get_cmdline_user_args()
	var base: GameMetrics = GameMetrics.load_default()
	if base == null:
		push_error("Could not load %s" % GameMetrics.DEFAULT_PATH)
		quit(1)
		return

	var started_ms: int = Time.get_ticks_msec()
	var metrics: GameMetrics = BallisticCalibrator.calibrate(base)
	var elapsed_ms: int = Time.get_ticks_msec() - started_ms
	var report: String = build_report(metrics)
	print(report)
	# Timing goes to stdout only, so the versioned report stays byte-identical across runs.
	print("Calibration time: %d ms" % elapsed_ms)

	for arg in args:
		if arg.begins_with("--report="):
			var path: String = arg.trim_prefix("--report=")
			var file: FileAccess = FileAccess.open(path, FileAccess.WRITE)
			if file == null:
				push_error("Could not write report to %s" % path)
				quit(1)
				return
			file.store_string(report)
			file.close()
			print("Report written to %s" % path)
		elif arg == "--write-metrics":
			var error: Error = ResourceSaver.save(metrics, GameMetrics.DEFAULT_PATH)
			if error != OK:
				push_error("Could not save metrics: %s" % error_string(error))
				quit(1)
				return
			print("Metrics written to %s" % GameMetrics.DEFAULT_PATH)
	quit(0)


func build_report(metrics: GameMetrics) -> String:
	var params: BallisticParameters = metrics.create_ballistic_parameters()
	var lines: PackedStringArray = []
	lines.append("# Ballistic calibration report")
	lines.append("")
	lines.append("Generated by `tools/ballistics/calibrate.sh` (Godot %s)." % Engine.get_version_info()["string"])
	lines.append("Units: 1.0 = one horizontal distance unit. Angles in degrees. Shots start at (0, 0);")
	lines.append("impact = descending crossing of y = 0. Model: docs/PHYSICS_MODEL.md.")
	lines.append_array(_parameters_section(metrics))
	lines.append_array(_full_throw_section(params))
	lines.append_array(_time_step_section(params))
	lines.append_array(_time_scale_section(metrics, params))
	lines.append_array(_wind_section(params))
	lines.append_array(_technique_section(params))
	lines.append_array(_half_throw_section(params))
	return "\n".join(lines) + "\n"


func _parameters_section(metrics: GameMetrics) -> PackedStringArray:
	return PackedStringArray([
		"",
		"## 1. Parameters",
		"",
		"| Parameter | Value | Class |",
		"|---|---|---|",
		"| K = v(%s)^2 / g | %.6f u | CALIBRATED (length; independent of time scale) |" % [_n(metrics.ballistic_k_reference_power, 0), metrics.ballistic_k],
		"| Wind acceleration / g per 1.0 wind | %.6f (= g / %.3f) | CALIBRATED (dimensionless ratio) |" % [metrics.wind_accel_ratio, 1.0 / metrics.wind_accel_ratio],
		"| Gravity g | %.6f u/s^2 | ESTIMATED / LOW (time scale) |" % metrics.gravity,
		"| power_scale = sqrt(K g) / %s | %.6f u/s per power point | derived |" % [_n(metrics.ballistic_k_reference_power, 0), metrics.power_scale()],
		"| v(%s) | %.6f u/s | derived |" % [_n(metrics.ballistic_k_reference_power, 0), metrics.power_scale() * metrics.ballistic_k_reference_power],
		"| Wind acceleration per 1.0 wind | %.6f u/s^2 | derived |" % metrics.wind_accel_per_unit(),
		"| Time step | %.6f s | engineering choice |" % metrics.time_step,
		"| Closed-form K (independent check) | %.9f u (simulator - closed form = %s) | analytic |" % [
			BallisticCalibrator.analytic_k_least_squares(),
			String.num_scientific(metrics.ballistic_k - BallisticCalibrator.analytic_k_least_squares())
		],
	])


func _full_throw_section(params: BallisticParameters) -> PackedStringArray:
	var lines := PackedStringArray([
		"",
		"## 2. Full Throw, zero wind (power %s, angle = 90 - D)" % _n(BallisticEvidence.FULL_THROW_POWER, 0),
		"",
		"Error metric: least squares of (impact - D) over D = 1..10.",
		"",
		"| D | Angle | Impact | Error |",
		"|---|---|---|---|",
	])
	var errors: PackedFloat64Array = BallisticCalibrator.full_throw_errors(params)
	var sum_abs: float = 0.0
	var max_abs: float = 0.0
	var sum_sq: float = 0.0
	for i in errors.size():
		var distance: float = BallisticEvidence.FULL_THROW_DISTANCES[i]
		lines.append("| %s | %s | %.4f | %+.4f |" % [
			_n(distance, 0), _n(BallisticEvidence.full_throw_angle(distance, 0.0), 0), distance + errors[i], errors[i]
		])
		sum_abs += absf(errors[i])
		max_abs = maxf(max_abs, absf(errors[i]))
		sum_sq += errors[i] * errors[i]
	lines.append("")
	lines.append("Mean absolute error: %.4f u. Maximum absolute error: %.4f u. RMS: %.4f u." % [
		sum_abs / errors.size(), max_abs, sqrt(sum_sq / errors.size())
	])
	return lines


func _time_step_section(params: BallisticParameters) -> PackedStringArray:
	var lines := PackedStringArray([
		"",
		"## 3. Time-step invariance",
		"",
		"| Shot | dt = %s | dt = %s | dt = %s | Max spread |" % BallisticEvidence.TIME_STEP_LABELS,
		"|---|---|---|---|---|",
	])
	var worst: float = 0.0
	for case in BallisticEvidence.TIME_STEP_CHECK_SHOTS:
		var impacts: PackedFloat64Array = []
		for dt in BallisticEvidence.TIME_STEP_VARIANTS:
			impacts.append(BallisticSolver.impact_distance(params.with_time_step(dt), case.x, case.y, case.z))
		var spread: float = 0.0
		for value in impacts:
			spread = maxf(spread, absf(value - impacts[0]))
		worst = maxf(worst, spread)
		lines.append("| angle %s, power %s, wind %s | %.12f | %.12f | %.12f | %s |" % [
			_n(case.x, 0), _n(case.y, 0), _n(case.z, 0), impacts[0], impacts[1], impacts[2], String.num_scientific(spread)
		])
	lines.append("")
	lines.append("Worst impact spread across time steps: %s u." % String.num_scientific(worst))
	return lines


func _time_scale_section(metrics: GameMetrics, params: BallisticParameters) -> PackedStringArray:
	var reference: float = BallisticEvidence.FLIGHT_TIME_REFERENCE_DISTANCE
	var result: BallisticResult = BallisticSolver.simulate(
		params, BallisticEvidence.full_throw_angle(reference, 0.0), BallisticEvidence.FULL_THROW_POWER
	)
	var lines := PackedStringArray([
		"",
		"## 4. Time scale (provisional)",
		"",
		"Gravity is chosen so that the Full Throw at D = %s lasts %.1f s (ESTIMATED / LOW)." % [
			_n(reference, 0), BallisticEvidence.PROVISIONAL_FULL_THROW_FLIGHT_TIME
		],
		"Measured with the simulator: flight time %.6f s; apex %.4f u above launch at x = %.4f." % [
			result.flight_time, -result.apex_y, result.apex_x
		],
		"",
		"Landing points depend only on K; gravity changes timing. Alternatives:",
		"",
		"| Flight time at D = %s | Gravity (u/s^2) | power_scale (u/s per point) | Wind accel per 1.0 (u/s^2) |" % _n(reference, 0),
		"|---|---|---|---|",
	])
	for flight_time in BallisticEvidence.FLIGHT_TIME_ALTERNATIVES:
		var gravity: float = BallisticCalibrator.gravity_for_flight_time(metrics, metrics.ballistic_k, flight_time)
		var variant: GameMetrics = BallisticCalibrator.with_values(metrics, metrics.ballistic_k, metrics.wind_accel_ratio, gravity)
		lines.append("| %.1f s | %.4f | %.6f | %.6f |" % [flight_time, gravity, variant.power_scale(), variant.wind_accel_per_unit()])
	return lines


func _wind_section(params: BallisticParameters) -> PackedStringArray:
	var lines := PackedStringArray([
		"",
		"## 5. Wind, Full Throw",
		"",
		"Correction = angle that really hits D with wind minus the angle that hits D without wind.",
		"Player rule: +%s degrees per 1.0 of tailwind, -%s per 1.0 of headwind." % [
			_n(BallisticEvidence.FULL_THROW_WIND_FACTOR, 0), _n(BallisticEvidence.FULL_THROW_WIND_FACTOR, 0)
		],
		"",
		"| D | Wind | Zero-wind angle | Angle with wind | Correction | Error vs rule |",
		"|---|---|---|---|---|---|",
	])
	var max_error: float = 0.0
	for row in BallisticCalibrator.wind_corrections(params):
		var error: float = row["error"]
		var distance: float = row["distance"]
		max_error = maxf(max_error, absf(error))
		lines.append("| %s | %+.1f | %.4f | %.4f | %+.4f | %+.4f |" % [
			_n(distance, 0), row["wind"], row["zero_angle"], row["wind_angle"], row["correction"], error
		])
	lines.append("")
	lines.append("Maximum correction error: %.4f degrees." % max_error)
	lines.append("")
	lines.append("Rule check: impact when aiming exactly at angle = 90 - D + 2 * wind (power 95).")
	lines.append("")
	lines.append("| D | Wind | Rule angle | Impact | Error |")
	lines.append("|---|---|---|---|---|")
	for distance in BallisticEvidence.WIND_RULE_CHECK_DISTANCES:
		for wind in BallisticEvidence.WIND_RULE_CHECK_WINDS:
			var angle: float = BallisticEvidence.full_throw_angle(distance, wind)
			var impact: float = BallisticSolver.impact_distance(params, angle, BallisticEvidence.FULL_THROW_POWER, wind)
			lines.append("| %s | %+.1f | %.1f | %.4f | %+.4f |" % [_n(distance, 0), wind, angle, impact, impact - distance])
	return lines


func _technique_section(params: BallisticParameters) -> PackedStringArray:
	var lines := PackedStringArray([
		"",
		"## 6. Predictions for fixed-angle techniques (same model, no tuning)",
		"",
		"Power = zero-wind power that hits D at the technique angle. Angle correction = change of",
		"angle (same power) that compensates 1.0 of wind; Power correction = change of power",
		"(same angle) that does it instead. NAN = no solution on that branch.",
		"",
		"| Angle | D | Power | Headwind: angle corr. | Tailwind: angle corr. | Headwind: power corr. | Tailwind: power corr. | Community wind factor |",
		"|---|---|---|---|---|---|---|---|",
	])
	for angle in BallisticEvidence.TECHNIQUE_ANGLES:
		for distance in BallisticEvidence.TECHNIQUE_DISTANCES:
			var p: Dictionary = BallisticCalibrator.technique_prediction(params, angle, distance)
			var claim: float = BallisticEvidence.COMMUNITY_WIND_FACTORS[angle]
			lines.append("| %s | %s | %.2f | %+.3f | %+.3f | %+.2f | %+.2f | %s |" % [
				_n(angle, 0), _n(distance, 0), p["power"], p["head_angle_correction"], p["tail_angle_correction"],
				p["head_power_correction"], p["tail_power_correction"], "-" if is_nan(claim) else "x%s" % _n(claim, 0)
			])
	lines.append("")
	lines.append("30-degree power table versus the community claim:")
	lines.append("")
	lines.append("| D | Community power | Model power | Model / community |")
	lines.append("|---|---|---|---|")
	for distance: float in BallisticEvidence.COMMUNITY_30_DEGREE_POWER:
		var claim_power: float = BallisticEvidence.COMMUNITY_30_DEGREE_POWER[distance]
		var model_power: float = BallisticSolver.solve_power(
			params, distance, BallisticEvidence.COMMUNITY_30_DEGREE_ANGLE, 0.0, BallisticEvidence.SEARCH_MIN_POWER, BallisticEvidence.SEARCH_MAX_POWER
		)
		lines.append("| %s | %.1f | %.2f | %.3f |" % [_n(distance, 0), claim_power, model_power, model_power / claim_power])
	return lines


func _half_throw_section(params: BallisticParameters) -> PackedStringArray:
	var research_power: float = BallisticEvidence.HALF_THROW_RESEARCH_POWER
	var best_power: float = BallisticCalibrator.half_throw_best_power(params)
	var best_errors: PackedFloat64Array = BallisticCalibrator.half_throw_errors(params, best_power)
	var research_errors: PackedFloat64Array = BallisticCalibrator.half_throw_errors(params, research_power)
	var lines := PackedStringArray([
		"",
		"## 7. Half Throw (angle = 90 - 2 * D), not calibrated",
		"",
		"Best single power (least squares over D = 1..10): %.3f. Research claim: %s." % [best_power, _n(research_power, 0)],
		"",
		"| D | Angle | Power that hits D exactly | Impact at best power | Impact at power %s | Angle that hits D at power %s | Degrees per unit at power %s |" % [
			_n(research_power, 0), _n(research_power, 0), _n(research_power, 0)
		],
		"|---|---|---|---|---|---|---|",
	])
	for i in BallisticEvidence.FULL_THROW_DISTANCES.size():
		var distance: float = BallisticEvidence.FULL_THROW_DISTANCES[i]
		var angle: float = BallisticEvidence.half_throw_angle(distance)
		var exact_power: float = BallisticSolver.solve_power(
			params, distance, angle, 0.0, BallisticEvidence.SEARCH_MIN_POWER, BallisticEvidence.SEARCH_MAX_POWER
		)
		var angle_at_research: float = BallisticSolver.solve_angle(
			params, distance, research_power, 0.0, BallisticEvidence.HIGH_BRANCH_MIN_ANGLE, BallisticEvidence.HIGH_BRANCH_MAX_ANGLE
		)
		lines.append("| %s | %s | %.3f | %.4f | %.4f | %.3f | %.3f |" % [
			_n(distance, 0), _n(angle, 0), exact_power, distance + best_errors[i], distance + research_errors[i],
			angle_at_research, (BallisticEvidence.FULL_THROW_ANGLE_BASE - angle_at_research) / distance
		])
	return lines


## Formats a float with a fixed number of decimals.
func _n(value: float, decimals: int) -> String:
	return String.num(value, decimals)
